# -*- coding: utf-8 -*-
"""
Per-subject revision sheets.

One page per subject, meant for the last read before the exam: the formulas,
the numbers worth memorising and the traps. Computer Networks and Engineering
Mathematics have no topic pages in the index, so their sheets are the only
notes those subjects carry and are written fuller than the rest.
"""

REVISION = {
    "algo": {
        "title": "Algorithms: revision sheet",
        "blocks": [
            ("h", "Growth order"),
            ("formula", "1 < log n < √n < n < n log n < n² < n³ < 2ⁿ < n!"),
            ("h", "Sorting"),
            ("table", [
                ["Algorithm", "Best", "Average", "Worst", "Space", "Stable"],
                ["Bubble", "O(n)", "O(n²)", "O(n²)", "O(1)", "yes"],
                ["Selection", "O(n²)", "O(n²)", "O(n²)", "O(1)", "no"],
                ["Insertion", "O(n)", "O(n²)", "O(n²)", "O(1)", "yes"],
                ["Merge", "O(n log n)", "O(n log n)", "O(n log n)", "O(n)", "yes"],
                ["Quick", "O(n log n)", "O(n log n)", "O(n²)", "O(log n)", "no"],
                ["Heap", "O(n log n)", "O(n log n)", "O(n log n)", "O(1)", "no"],
                ["Counting", "O(n+k)", "O(n+k)", "O(n+k)", "O(n+k)", "yes"],
            ]),
            ("h", "Graphs"),
            ("table", [
                ["Algorithm", "Time", "Handles"],
                ["BFS / DFS", "O(V+E)", "unweighted"],
                ["Dijkstra (heap)", "O((V+E) log V)", "non-negative weights"],
                ["Bellman-Ford", "O(V·E)", "negative edges, detects negative cycles"],
                ["Floyd-Warshall", "Θ(V³)", "all pairs, negative edges"],
                ["Prim (heap)", "O(E log V)", "MST, dense graphs"],
                ["Kruskal", "O(E log E)", "MST, sparse graphs"],
            ]),
            ("h", "Master theorem"),
            ("formula", "T(n) = a·T(n/b) + f(n);  compare f(n) with n^(log_b a)"),
            ("h", "Dynamic programming"),
            ("table", [
                ["Problem", "Recurrence core", "Time"],
                ["LCS", "match ⟹ 1 + diagonal, else max of two", "Θ(mn)"],
                ["0/1 knapsack", "max(skip, take)", "Θ(nW)"],
                ["Matrix chain", "min over split points", "Θ(n³)"],
                ["Floyd-Warshall", "min(direct, via k)", "Θ(n³)"],
            ]),
            ("key", "Comparison sorting cannot beat Ω(n log n): a decision tree with n! leaves has height Θ(n log n). Counting, radix and bucket sort escape it by not comparing."),
            ("warn", "Quick sort's worst case is sorted input with a first or last pivot. Greedy fails 0/1 knapsack. Dijkstra fails on negative edges. Those three are the most examined traps in this subject."),
        ],
    },

    "ds": {
        "title": "Programming and Data Structures: revision sheet",
        "blocks": [
            ("h", "Operation costs"),
            ("table", [
                ["Structure", "Access", "Search", "Insert", "Delete"],
                ["Array", "O(1)", "O(n)", "O(n)", "O(n)"],
                ["Sorted array", "O(1)", "O(log n)", "O(n)", "O(n)"],
                ["Linked list", "O(n)", "O(n)", "O(1) given the node", "O(1) given the node"],
                ["Stack / queue", "—", "—", "O(1)", "O(1)"],
                ["BST (balanced)", "O(log n)", "O(log n)", "O(log n)", "O(log n)"],
                ["Heap", "O(1) min/max", "O(n)", "O(log n)", "O(log n)"],
                ["Hash table", "—", "O(1) avg", "O(1) avg", "O(1) avg"],
            ]),
            ("h", "Trees"),
            ("bullets", [
                "A binary tree of height h has at most 2^(h+1) − 1 nodes.",
                "Nodes with two children = leaves − 1.",
                "Inorder of a BST is sorted.",
                "Inorder plus preorder (or postorder) determines the tree; preorder plus postorder does not.",
            ]),
            ("h", "Heap indices"),
            ("formula", "0-based: left = 2i+1, right = 2i+2, parent = ⌊(i−1)/2⌋"),
            ("h", "Address arithmetic"),
            ("formula", "Row major: a[i][j] = base + ((i × cols) + j) × size"),
            ("formula", "Column major: a[i][j] = base + ((j × rows) + i) × size"),
            ("h", "C traps"),
            ("bullets", [
                "p + i advances by i × sizeof(*p) bytes.",
                "An array argument decays to a pointer, so sizeof gives the pointer size.",
                "Signed overflow is undefined; unsigned wraps.",
                "Mixing signed and unsigned promotes to unsigned: −1 < 1u is false.",
                "struct size includes padding; union size is its largest member.",
            ]),
            ("key", "Stack push-pop orderings for n items number C(n) = (2n)!/(n!(n+1)!): 5 for n = 3, 14 for n = 4."),
        ],
    },

    "os": {
        "title": "Operating Systems: revision sheet",
        "blocks": [
            ("h", "Scheduling"),
            ("formula", "Turnaround = completion − arrival;  Waiting = turnaround − burst"),
            ("table", [
                ["Algorithm", "Preemptive", "Starvation"],
                ["FCFS", "no", "no"],
                ["SJF", "no", "possible"],
                ["SRTF", "yes", "possible"],
                ["Round robin", "yes", "no"],
                ["Priority", "either", "possible, cure by ageing"],
                ["HRRN", "no", "no"],
            ]),
            ("key", "SJF is optimal for average waiting time. Round robin is best for response time. Both facts are asked directly."),
            ("h", "Deadlock"),
            ("bullets", [
                "Coffman: mutual exclusion, hold and wait, no preemption, circular wait — all four at once.",
                "Banker's algorithm avoids by refusing any request that leaves an unsafe state.",
                "Unsafe is not deadlocked; it is merely not provably safe.",
            ]),
            ("h", "Memory"),
            ("formula", "EAT with TLB = h·(TLB + M) + (1 − h)·(TLB + 2M)"),
            ("formula", "EAT with page faults = (1 − p)·M + p·fault service time"),
            ("bullets", [
                "Paging: no external fragmentation, internal up to one page.",
                "Segmentation: no internal fragmentation, external instead.",
                "Belady's anomaly: FIFO only. LRU and OPT are stack algorithms and immune.",
            ]),
            ("h", "Disk"),
            ("formula", "Access time = seek + rotational latency + transfer"),
            ("note", "Average rotational latency is half a rotation: 4.17 ms at 7200 rpm."),
            ("warn", "Producer-consumer: take the counting semaphore before the mutex. The reverse order deadlocks, and it is the standard trick question."),
        ],
    },

    "dbms": {
        "title": "Databases: revision sheet",
        "blocks": [
            ("h", "Keys"),
            ("bullets", [
                "Super key: identifies uniquely. Candidate key: minimal super key. Primary: the chosen one.",
                "X is a candidate key when X⁺ is every attribute and no proper subset is.",
            ]),
            ("h", "Normal forms"),
            ("table", [
                ["Form", "Removes"],
                ["1NF", "non-atomic values"],
                ["2NF", "partial dependency on part of a key"],
                ["3NF", "transitive dependency on non-prime attributes"],
                ["BCNF", "any determinant that is not a super key"],
            ]),
            ("key", "3NF permits X → Y when Y is prime; BCNF does not. BCNF is always achievable losslessly but may lose dependency preservation."),
            ("formula", "Lossless binary decomposition ⟺ (R1 ∩ R2) → R1 or (R1 ∩ R2) → R2"),
            ("h", "Transactions"),
            ("table", [
                ["Level", "Dirty read", "Non-repeatable", "Phantom"],
                ["Read uncommitted", "yes", "yes", "yes"],
                ["Read committed", "no", "yes", "yes"],
                ["Repeatable read", "no", "no", "yes"],
                ["Serialisable", "no", "no", "no"],
            ]),
            ("bullets", [
                "Conflict serialisable ⟺ acyclic precedence graph.",
                "2PL guarantees serialisability; strict 2PL also prevents cascading rollback.",
                "Wait-die is non-preemptive, wound-wait is preemptive; both use timestamps.",
            ]),
            ("h", "SQL"),
            ("note", "Evaluation order is FROM, WHERE, GROUP BY, HAVING, SELECT, ORDER BY. WHERE cannot see a SELECT alias; ORDER BY can."),
            ("warn", "NULL is unknown: x = NULL is never true, and NOT IN with any NULL returns no rows. Always use IS NULL."),
        ],
    },

    "cao": {
        "title": "Computer Organisation: revision sheet",
        "blocks": [
            ("h", "Performance"),
            ("formula", "CPU time = instruction count × CPI × clock period"),
            ("formula", "Amdahl: speedup = 1 / ((1 − f) + f/s)"),
            ("h", "Pipelining"),
            ("formula", "Cycles = k + (n − 1);  speedup = n·k/(k + n − 1) → k"),
            ("formula", "Clock period = slowest stage + latch delay"),
            ("bullets", [
                "Structural hazard: a resource clash.",
                "Data hazard: RAW is true; WAR and WAW vanish with renaming.",
                "Control hazard: an unresolved branch.",
                "Forwarding removes most RAW stalls but not load-use.",
            ]),
            ("h", "Cache"),
            ("formula", "Address = tag | index | offset"),
            ("formula", "offset bits = log₂(block size);  index bits = log₂(number of sets)"),
            ("formula", "Average access = h·tc + (1 − h)·tm  (simultaneous)"),
            ("formula", "Average access = tc + (1 − h)·tm  (hierarchical)"),
            ("table", [
                ["Mapping", "Comparisons", "Conflict misses"],
                ["Direct", "1", "most"],
                ["k-way", "k", "fewer"],
                ["Fully associative", "all", "none"],
            ]),
            ("h", "Addressing modes"),
            ("note", "Memory accesses for the operand: immediate and register 0, direct and register indirect 1, memory indirect 2."),
            ("warn", "Read whether the cache model is simultaneous or hierarchical. The same hit ratio gives different answers under each."),
        ],
    },

    "toc": {
        "title": "Theory of Computation: revision sheet",
        "blocks": [
            ("h", "The hierarchy"),
            ("table", [
                ["Type", "Language", "Machine", "Grammar"],
                ["3", "Regular", "Finite automaton", "A → aB | a"],
                ["2", "Context-free", "Pushdown automaton", "A → α"],
                ["1", "Context-sensitive", "Linear bounded automaton", "αAβ → αγβ"],
                ["0", "Recursively enumerable", "Turing machine", "α → β"],
            ]),
            ("key", "Separating examples: aⁿbⁿ is context-free but not regular; aⁿbⁿcⁿ is context-sensitive but not context-free."),
            ("h", "Closure"),
            ("table", [
                ["Class", "Union", "Intersection", "Complement"],
                ["Regular", "yes", "yes", "yes"],
                ["Context-free", "yes", "no", "no"],
                ["Recursive", "yes", "yes", "yes"],
                ["Recursively enumerable", "yes", "yes", "no"],
            ]),
            ("h", "Automata"),
            ("bullets", [
                "NFA and DFA accept the same languages; subset construction can cost 2ⁿ states.",
                "Moore output length is n + 1, Mealy is n.",
                "The pumping lemma disproves regularity; passing it proves nothing.",
            ]),
            ("h", "Decidability"),
            ("bullets", [
                "L is recursive ⟺ L and its complement are both recursively enumerable.",
                "The halting problem is recursively enumerable but not recursive.",
                "Rice: every non-trivial property of the recognised language is undecidable.",
            ]),
        ],
    },

    "dl": {
        "title": "Digital Logic: revision sheet",
        "blocks": [
            ("h", "Number systems"),
            ("bullets", [
                "2's complement of n bits: −2ⁿ⁻¹ to 2ⁿ⁻¹ − 1, single zero.",
                "1's complement: −(2ⁿ⁻¹ − 1) to 2ⁿ⁻¹ − 1, two zeros.",
                "Binary to Gray: g(i) = b(i+1) ⊕ b(i). Gray to binary: b(i) = b(i+1) ⊕ g(i).",
            ]),
            ("h", "IEEE 754"),
            ("table", [
                ["", "Sign", "Exponent", "Mantissa", "Bias"],
                ["Single", "1", "8", "23", "127"],
                ["Double", "1", "11", "52", "1023"],
            ]),
            ("h", "Boolean identities"),
            ("formula", "A + AB = A;  A + A'B = A + B;  (AB)' = A' + B';  (A+B)' = A'B'"),
            ("h", "Adders"),
            ("formula", "Full adder: Sum = A ⊕ B ⊕ Cin,  Cout = AB + Cin(A ⊕ B)"),
            ("note", "Ripple carry delay is O(n); carry look-ahead computes carries in constant gate delay per block using G = AB and P = A ⊕ B."),
            ("h", "Combinational blocks"),
            ("bullets", [
                "n select lines choose among 2ⁿ multiplexer inputs.",
                "A 2ⁿ-to-1 mux implements any n-variable function directly.",
                "A decoder has n inputs and 2ⁿ outputs; an encoder is the reverse.",
                "Five 4-to-1 muxes build a 16-to-1.",
            ]),
            ("h", "Flip-flops"),
            ("table", [
                ["Type", "Q⁺"],
                ["SR", "S + R'Q"],
                ["D", "D"],
                ["JK", "JQ' + K'Q"],
                ["T", "T ⊕ Q"],
            ]),
            ("key", "A mod-m counter needs ⌈log₂ m⌉ flip-flops. Ring counters give n states from n flip-flops, Johnson counters 2n."),
        ],
    },

    "cd": {
        "title": "Compiler Design: revision sheet",
        "blocks": [
            ("h", "Phases and their errors"),
            ("table", [
                ["Phase", "Catches"],
                ["Lexical", "illegal character, unterminated string"],
                ["Syntax", "missing semicolon, unbalanced brackets"],
                ["Semantic", "type mismatch, undeclared variable"],
                ["Run time", "division by zero — not a compiler error"],
            ]),
            ("h", "Parsers"),
            ("table", [
                ["Parser", "Direction", "Lookahead for reduce"],
                ["LL(1)", "top-down", "FIRST and FOLLOW to pick a production"],
                ["SLR(1)", "bottom-up", "FOLLOW of the left side"],
                ["LALR(1)", "bottom-up", "merged per-item lookahead"],
                ["CLR(1)", "bottom-up", "per-item lookahead"],
            ]),
            ("key", "Power: SLR(1) ⊂ LALR(1) ⊂ CLR(1). Merging CLR states into LALR can add reduce-reduce conflicts but never shift-reduce ones."),
            ("h", "Grammar preparation"),
            ("formula", "Left recursion: A → Aα | β  ⟹  A → βA', A' → αA' | ε"),
            ("formula", "Left factoring: A → αβ | αγ  ⟹  A → αA', A' → β | γ"),
            ("warn", "Left recursion breaks top-down parsers only. LR parsers handle it; they cannot handle ambiguity."),
            ("h", "Attributes"),
            ("bullets", [
                "Synthesised: from children, evaluable bottom-up, fits LR.",
                "Inherited: from parent or left siblings.",
                "S-attributed ⊂ L-attributed; L-attributed is what one pass can evaluate.",
            ]),
            ("h", "Optimisation"),
            ("note", "Machine-independent: constant folding and propagation, common subexpression elimination, dead code, copy propagation, loop-invariant motion, strength reduction. Machine-dependent: register allocation, instruction scheduling, peephole."),
        ],
    },

    "cn": {
        "title": "Computer Networks: revision sheet",
        "blocks": [
            ("p", "Computer Networks carries about 8 marks in the CS paper. This sheet is the whole subject in outline."),
            ("h", "The layers"),
            ("table", [
                ["OSI layer", "TCP/IP", "Unit", "Job"],
                ["Application", "Application", "data", "HTTP, DNS, SMTP"],
                ["Transport", "Transport", "segment", "TCP, UDP, ports"],
                ["Network", "Internet", "packet", "IP, routing"],
                ["Data link", "Link", "frame", "MAC, error detection"],
                ["Physical", "Link", "bits", "signalling"],
            ]),
            ("h", "Addressing"),
            ("formula", "A /n prefix leaves 32 − n host bits, giving 2^(32−n) − 2 usable hosts"),
            ("example", "192.168.1.0/24 has 254 usable addresses; /26 subnets give 62 each."),
            ("bullets", [
                "Class A 1–126, B 128–191, C 192–223 by first octet.",
                "Private ranges: 10/8, 172.16/12, 192.168/16.",
                "The all-zero address is the network and the all-one is the broadcast, hence the −2.",
            ]),
            ("h", "Transport"),
            ("table", [
                ["", "TCP", "UDP"],
                ["Connection", "yes, three-way handshake", "no"],
                ["Reliability", "acknowledgements and retransmission", "none"],
                ["Ordering", "yes", "no"],
                ["Header", "20 bytes minimum", "8 bytes"],
                ["Use", "web, mail, file transfer", "DNS, streaming, games"],
            ]),
            ("h", "Sliding window"),
            ("formula", "Efficiency = W / (1 + 2a),  where a = propagation time / transmission time"),
            ("formula", "Stop and wait: W = 1.  Go-Back-N: W = N.  Selective repeat: W ≤ 2^(k−1) for k sequence bits"),
            ("h", "Error handling"),
            ("bullets", [
                "Parity detects odd numbers of bit errors only.",
                "CRC detects burst errors up to the degree of the generator polynomial.",
                "Hamming distance d detects d − 1 errors and corrects ⌊(d−1)/2⌋.",
            ]),
            ("h", "Routing"),
            ("bullets", [
                "Distance vector (RIP): Bellman-Ford, counts to infinity, split horizon helps.",
                "Link state (OSPF): Dijkstra over a flooded topology map.",
                "BGP: path vector, between autonomous systems.",
            ]),
            ("key", "CSMA/CD gives Ethernet its minimum frame size: a station must still be transmitting when the furthest collision returns, so frame time ≥ 2 × propagation delay."),
        ],
    },

    "maths": {
        "title": "Engineering Mathematics: revision sheet",
        "blocks": [
            ("p", "Engineering Mathematics is about 13 marks in the CS paper, spread over discrete mathematics, linear algebra, calculus and probability."),
            ("h", "Set theory and relations"),
            ("bullets", [
                "A relation is reflexive, symmetric and transitive ⟹ equivalence relation ⟹ it partitions the set.",
                "Reflexive, antisymmetric and transitive ⟹ partial order.",
                "Functions from a set of size m to one of size n: nᵐ. Injections need n ≥ m.",
            ]),
            ("h", "Counting"),
            ("formula", "C(n, r) = n! / (r!(n − r)!);  P(n, r) = n! / (n − r)!"),
            ("formula", "Inclusion-exclusion: |A ∪ B| = |A| + |B| − |A ∩ B|"),
            ("note", "Pigeonhole: n items in k boxes force some box to hold at least ⌈n/k⌉."),
            ("h", "Graph theory"),
            ("bullets", [
                "Σ degrees = 2|E|.",
                "A tree on n vertices has n − 1 edges; a complete graph has n(n−1)/2.",
                "Euler circuit ⟺ connected and every degree even.",
                "A simple planar graph satisfies V − E + F = 2 and E ≤ 3V − 6.",
            ]),
            ("h", "Linear algebra"),
            ("bullets", [
                "Ax = b has a unique solution ⟺ det(A) ≠ 0 ⟺ rank = n.",
                "Σ eigenvalues = trace; Π eigenvalues = determinant.",
                "A symmetric real matrix has real eigenvalues and orthogonal eigenvectors.",
                "rank + nullity = number of columns.",
            ]),
            ("h", "Calculus"),
            ("bullets", [
                "Rolle and the mean value theorem need continuity on [a,b] and differentiability on (a,b).",
                "L'Hôpital applies only to 0/0 and ∞/∞.",
                "A maximum needs f'(x) = 0 and f''(x) < 0.",
            ]),
            ("h", "Probability"),
            ("formula", "Bayes: P(A|B) = P(B|A)·P(A) / P(B)"),
            ("table", [
                ["Distribution", "Mean", "Variance"],
                ["Binomial(n, p)", "np", "np(1−p)"],
                ["Poisson(λ)", "λ", "λ"],
                ["Uniform(a, b)", "(a+b)/2", "(b−a)²/12"],
                ["Exponential(λ)", "1/λ", "1/λ²"],
            ]),
            ("key", "Mutually exclusive events with non-zero probability are never independent. That single sentence resolves a surprising number of options."),
        ],
    },
}
