package com.gatemaster.app.core.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Study-material model, mirroring assets/content_index.json.
 *
 * The index is generated by tools/build_content_index.py from whatever is in
 * the assets folder, so adding a topic means dropping in a file and re-running
 * the script — not editing Kotlin.
 */

@Serializable
enum class ContentType {
    @SerialName("html")
    HTML,

    @SerialName("pdf")
    PDF,
}

/** Where a piece of content lives. Paths are relative to the assets root. */
@Serializable
data class ContentRef(
    val type: ContentType,
    val path: String,
) {
    /** Asset URL form that WebView understands. */
    val assetUrl: String get() = "file:///android_asset/$path"
}

@Serializable
data class Topic(
    val id: String,
    val title: String,
    val order: Int,
    val content: ContentRef,
)

/**
 * A subject-level PDF handout. Kept separate from [Topic] because these are
 * long-form documents to read end to end, not individual concepts.
 */
@Serializable
data class ReferenceNote(
    val id: String,
    val title: String,
    val order: Int,
    val sizeBytes: Long = 0,
    val content: ContentRef,
)

@Serializable
data class Subject(
    val id: String,
    val name: String,
    val shortName: String,
    /** Approximate marks this subject carries in the GATE CS paper. */
    val weightage: Int,
    val order: Int,
    val topics: List<Topic> = emptyList(),
    val referenceNotes: List<ReferenceNote> = emptyList(),
    val shortNotes: ContentRef? = null,
) {
    /** True when the subject is advertised but has nothing behind it yet. */
    val isEmpty: Boolean
        get() = topics.isEmpty() && referenceNotes.isEmpty() && shortNotes == null

    val itemCount: Int
        get() = topics.size + referenceNotes.size + if (shortNotes != null) 1 else 0
}

@Serializable
data class Paper(
    val id: String,
    val year: Int,
    val title: String,
    val paper: ContentRef,
    val answerKey: ContentRef? = null,
    val sizeBytes: Long = 0,
)

@Serializable
data class ContentIndex(
    val schemaVersion: Int,
    val generatedAt: String = "",
    val subjects: List<Subject> = emptyList(),
    val papers: List<Paper> = emptyList(),
) {
    companion object {
        val EMPTY = ContentIndex(schemaVersion = 0)
    }
}
