package com.gatemaster.app.core.model

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Study-material model, mirroring assets/content_index.json.
 *
 * The index is generated by tools/build_content_index.py from whatever is in
 * the assets folder, so adding a topic means dropping in a file and re-running
 * the script — not editing Kotlin.
 *
 * The top level is the GATE **paper** (branch). All 30 papers are present.
 * Every subject carries its official syllabus; a subject may additionally carry
 * notes, reference PDFs and short notes where we have them.
 */

@Serializable
enum class ContentType {
    @SerialName("html")
    HTML,

    @SerialName("pdf")
    PDF,
}

/** Where a piece of content lives. Paths are relative to the assets root. */
@Serializable
data class ContentRef(
    val type: ContentType,
    val path: String,
)

@Serializable
data class Topic(
    val id: String,
    val title: String,
    val order: Int,
    val content: ContentRef,
)

/**
 * A subject-level PDF handout. Kept separate from [Topic] because these are
 * long-form documents to read end to end, not individual concepts.
 */
@Serializable
data class ReferenceNote(
    val id: String,
    val title: String,
    val order: Int,
    val sizeBytes: Long = 0,
    val content: ContentRef,
)

@Serializable
data class Subject(
    val id: String,
    val name: String,
    val shortName: String,
    /** Approximate marks this subject carries in its paper. */
    val weightage: Int,
    val order: Int,
    /** Official GATE syllabus for this subject. Present even without notes. */
    val syllabus: List<String> = emptyList(),
    val topics: List<Topic> = emptyList(),
    val referenceNotes: List<ReferenceNote> = emptyList(),
    val shortNotes: ContentRef? = null,
) {
    val noteCount: Int
        get() = topics.size + referenceNotes.size + if (shortNotes != null) 1 else 0

    /** True when only the syllabus is available, with no notes behind it. */
    val isSyllabusOnly: Boolean get() = noteCount == 0

    /** Nothing at all to show — neither notes nor a syllabus. */
    val isEmpty: Boolean get() = noteCount == 0 && syllabus.isEmpty()
}

/** How much detail we hold for a paper. */
@Serializable
enum class BranchDetail {
    /** Full subject list with per-subject syllabus. */
    @SerialName("full")
    FULL,

    /** Section names only. */
    @SerialName("outline")
    OUTLINE,
}

/** One GATE paper, e.g. CS, ME, EE. */
@Serializable
data class Branch(
    val id: String,
    /** Official GATE paper code, e.g. "CS", "ME". */
    val code: String,
    val name: String,
    val shortName: String,
    val order: Int,
    val detail: BranchDetail = BranchDetail.OUTLINE,
    val hasNotes: Boolean = false,
    val noteCount: Int = 0,
    val subjects: List<Subject> = emptyList(),
    val paperIds: List<String> = emptyList(),
) {
    val totalTopics: Int get() = subjects.sumOf { it.noteCount }

    val subjectsWithNotes: Int get() = subjects.count { !it.isSyllabusOnly }
}

@Serializable
data class Paper(
    val id: String,
    val year: Int,
    val title: String,
    val paper: ContentRef,
    val answerKey: ContentRef? = null,
    val sizeBytes: Long = 0,
)

@Serializable
data class ContentIndex(
    val schemaVersion: Int,
    val generatedAt: String = "",
    val branches: List<Branch> = emptyList(),
    val papers: List<Paper> = emptyList(),
) {
    fun branch(id: String): Branch? = branches.firstOrNull { it.id == id }

    /** Papers available to a branch. Only CS has previous-year papers so far. */
    fun papersFor(branch: Branch): List<Paper> =
        papers.filter { it.id in branch.paperIds }

    companion object {
        const val DEFAULT_BRANCH = "cs"
        val EMPTY = ContentIndex(schemaVersion = 0)
    }
}
