#!/usr/bin/env python3
"""
Renders the bundled revision notes from a single authored source.

Every article in assets/<subject>/ is generated by this script from the note
definitions in tools/notes/. Nothing under assets is hand-edited any more, and
nothing is copied from anywhere: the previous articles were scraped, carried a
tutorial site's markup, and hotlinked 722 of their diagrams, which made the app
impossible to publish.

The notes are deliberately short. A GATE candidate revising on a phone wants the
definition, the formula, the one worked case and the trap -- not a tutorial. The
long form is what the previous content got wrong for this medium.

Markup uses the vocabulary reader.css already styles, so generated notes look
exactly like the rest of the app: callouts, formula plaques, complexity chips,
code panels and scrollable tables.

Run:  python tools/write_notes.py           # write every note
      python tools/write_notes.py --check   # report coverage, write nothing
"""

from __future__ import annotations

import html
import io
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
ASSETS = os.path.normpath(os.path.join(ROOT, "..", "app", "src", "main", "assets"))
INDEX = os.path.join(ASSETS, "content_index.json")

# Inline tags an author may use inside note text. Everything else is escaped,
# so a stray "<" in "a < b" cannot break the page.
INLINE = ("sup", "sub", "code", "b", "i", "br")


def text(raw: str) -> str:
    """Escape author text, then let the small inline whitelist back through."""
    out = html.escape(raw, quote=False)
    for tag in INLINE:
        out = out.replace("&lt;%s&gt;" % tag, "<%s>" % tag)
        out = out.replace("&lt;/%s&gt;" % tag, "</%s>" % tag)
    return out


# -- blocks -----------------------------------------------------------------
#
# A note is a list of (kind, payload) pairs. Tuples keep the authored source
# compact, which matters when there are 217 of them.

CALLOUTS = {
    "def": ("gm-definition", "Definition"),
    "note": ("gm-note", "Note"),
    "example": ("gm-example", "Example"),
    "solution": ("gm-solution", "Solution"),
    "warn": ("gm-warn", "Careful"),
    "key": ("gm-key", "Key point"),
    "syntax": ("gm-syntax", "Syntax"),
}


def render_block(kind: str, payload) -> str:
    if kind == "h":
        return "<h2>%s</h2>" % text(payload)

    if kind == "p":
        return "<p>%s</p>" % text(payload)

    if kind in CALLOUTS:
        cls, label = CALLOUTS[kind]
        return '<div class="gm-callout %s" data-label="%s"><p>%s</p></div>' % (
            cls, label, text(payload),
        )

    if kind == "formula":
        return '<div class="gm-formula"><p>%s</p></div>' % text(payload)

    if kind == "complexity":
        label, value = payload
        return '<p class="gm-complexity" data-label="%s">%s</p>' % (
            text(label), text(value),
        )

    if kind == "step":
        return '<p class="gm-step">%s</p>' % text(payload)

    if kind == "bullets":
        items = "".join("<li>%s</li>" % text(item) for item in payload)
        return "<ul>%s</ul>" % items

    if kind == "steps":
        items = "".join("<li>%s</li>" % text(item) for item in payload)
        return "<ol>%s</ol>" % items

    if kind == "table":
        head, rows = payload[0], payload[1:]
        head_html = "".join("<th>%s</th>" % text(c) for c in head)
        body = "".join(
            "<tr>%s</tr>" % "".join("<td>%s</td>" % text(c) for c in row)
            for row in rows
        )
        return (
            '<div class="gm-table"><table><thead><tr>%s</tr></thead>'
            "<tbody>%s</tbody></table></div>" % (head_html, body)
        )

    if kind == "code":
        lang, body = payload
        lines = "".join(
            '<div class="line">%s</div>' % (text(line) or "&nbsp;")
            for line in body.split("\n")
        )
        return '<div class="gm-code" data-lang="%s"><div class="gm-code-body">%s</div></div>' % (
            text(lang), lines,
        )

    raise SystemExit("unknown block kind: %r" % kind)


PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<link rel="stylesheet" href="../reader.css">
</head>
<body>
<h1>{title}</h1>
{body}
</body>
</html>
"""


def render(title: str, blocks) -> str:
    body = "\n".join(render_block(kind, payload) for kind, payload in blocks)
    return PAGE.format(title=text(title), body=body)


# -- the index --------------------------------------------------------------


def indexed_topics():
    """topic id -> (title, asset path), for every topic in every paper."""
    index = json.load(io.open(INDEX, encoding="utf-8"))
    found = {}
    for branch in index["branches"]:
        for subject in branch.get("subjects", []):
            for topic in subject.get("topics", []):
                found.setdefault(
                    topic["id"], (topic["title"], topic["content"]["path"]),
                )
    return found


def indexed_short_notes():
    """subject id -> (subject name, asset path) for each revision sheet."""
    index = json.load(io.open(INDEX, encoding="utf-8"))
    found = {}
    for branch in index["branches"]:
        for subject in branch.get("subjects", []):
            ref = subject.get("shortNotes")
            if ref:
                found.setdefault(subject["id"], (subject["name"], ref["path"]))
    return found


def load_notes():
    """Every NOTES dict under tools/notes/, merged."""
    sys.path.insert(0, ROOT)
    notes_dir = os.path.join(ROOT, "notes")
    merged = {}
    titles = {}
    for name in sorted(os.listdir(notes_dir)):
        if not name.endswith(".py") or name.startswith("_"):
            continue
        module = __import__("notes.%s" % name[:-3], fromlist=["NOTES"])
        for topic_id, note in getattr(module, "NOTES", {}).items():
            if topic_id in merged:
                raise SystemExit("%s is defined twice" % topic_id)
            merged[topic_id] = note.get("blocks", note) if isinstance(note, dict) else note
            if isinstance(note, dict) and note.get("title"):
                titles[topic_id] = note["title"]
    return merged, titles


def main() -> int:
    check_only = "--check" in sys.argv
    topics = indexed_topics()
    notes, retitled = load_notes()

    unknown = sorted(set(notes) - set(topics))
    if unknown:
        print("These notes name a topic the index does not have:")
        for topic_id in unknown:
            print("  %s" % topic_id)
        return 1

    written = 0
    missing = []
    for topic_id, (title, path) in sorted(topics.items()):
        blocks = notes.get(topic_id)
        if blocks is None:
            missing.append((topic_id, title))
            continue
        # An authored title wins: several of the scraped headings carried
        # mojibake or a stray "for GATE Exam [2024]".
        page = render(retitled.get(topic_id, title), blocks)
        if not check_only:
            target = os.path.join(ASSETS, path.replace("/", os.sep))
            os.makedirs(os.path.dirname(target), exist_ok=True)
            with io.open(target, "w", encoding="utf-8", newline="\n") as fh:
                fh.write(page)
        written += 1

    print("%d of %d topics have notes" % (written, len(topics)))
    if missing:
        print("\nStill to write (%d):" % len(missing))
        for topic_id, title in missing:
            print("  %-30s %s" % (topic_id, title))
    # The revision sheets are the same rendering one level up: a formula sheet
    # for a whole subject rather than a page for one topic.
    revision = __import__("notes._revision", fromlist=["REVISION"]).REVISION
    sheets = indexed_short_notes()
    written_sheets = 0
    for subject_id, (name, path) in sorted(sheets.items()):
        sheet = revision.get(subject_id)
        if sheet is None:
            continue
        page = render(sheet.get("title", "%s: revision sheet" % name), sheet["blocks"])
        if not check_only:
            target = os.path.join(ASSETS, path.replace("/", os.sep))
            with io.open(target, "w", encoding="utf-8", newline="\n") as fh:
                fh.write(page)
        written_sheets += 1

    print("%d of %d revision sheets have notes" % (written_sheets, len(sheets)))
    missing_sheets = sorted(set(sheets) - set(revision))
    if missing_sheets:
        print("  still to write: %s" % ", ".join(missing_sheets))

    if not check_only:
        print("\nWrote %d articles and %d revision sheets." % (written, written_sheets))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
